In [3]:
import pandas as pd

pd.__version__

'2.2.2'

In [9]:
import os
print(os.getcwd())


C:\Users\ElSenior\ml_zoomcamp\homeworks


In [11]:
data = pd.read_csv('laptops.csv')

In [15]:
data.head(10)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   
5  MSI Crosshair 17 C12VF-264XES Intel Core i7-12...    New     MSI   
6  Lenovo Thinkpad E14 Gen 4 AMD Ryzen 5 5625U/8G...    New  Lenovo   
7  ASUS VivoBook 15 F515JA-EJ2882W Intel Core i7-...    New    Asus   
8  Medion Akoya E15415 Intel Core i5-10210U/8GB/2...    New  Medion   
9  HP Victus 16-d1038ns Intel Core i7-12700H/16GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   
5   Crosshair  Intel Core i7   32     1000          SSD  RTX 4060    17.3   
6    ThinkPad    AMD Ryzen 5    8      256          SSD       NaN    14.0   
7    VivoBook  Intel Core i7    8      512          SSD       NaN    15.6   
8       Akoya  Intel Core i5    8      256          SSD       NaN    15.6   
9      Victus  Intel Core i7   16      512          SSD  RTX 3050    16.1   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01  
5    No      1699.00  
6    No       909.00  
7    No       809.01  
8    No       519.00  
9    No      1149.00

In [17]:
data.count()

Laptop          2160
Status          2160
Brand           2160
Model           2160
CPU             2160
RAM             2160
Storage         2160
Storage type    2118
GPU              789
Screen          2156
Touch           2160
Final Price     2160
dtype: int64

In [23]:
data.nunique(0)

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

In [29]:
data[data['Brand'] == 'Dell']['Final Price'].max()

3936.0

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [31]:
data['Screen'].median()

15.6

In [45]:
data['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [39]:
data['Screen'].fillna(15.6, inplace = True)

C:\Users\ElSenior\AppData\Local\Temp\ipykernel_14180\3340779401.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Screen'].fillna(15.6, inplace = True)


In [47]:
data['Screen'].median()

15.6

In [67]:
X = data[data['Brand']=='Innjoo'].loc[:,['RAM','Storage','Screen']]

In [81]:
import numpy as np
tX = np.transpose(X)
print(tX)

          1478   1479  1480  1481   1482   1483
RAM        8.0    8.0   4.0   6.0    6.0    6.0
Storage  256.0  512.0  64.0  64.0  128.0  128.0
Screen    15.6   15.6  14.1  14.1   14.1   14.1


In [83]:
XTX = np.dot(tX, X)

In [85]:
print(XTX)

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [87]:
inXTX = np.linalg.inv(XTX)
print(inXTX)

[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [91]:
y= np.array([1100, 1300, 800, 900, 1000, 1100])

In [93]:
print(y)

[1100 1300  800  900 1000 1100]


In [99]:
w = np.dot(np.dot(inXTX, tX),y)

In [101]:
print(w)

[45.58076606  0.42783519 45.29127938]


In [103]:
w.sum()

91.29988062995457